### ISSUE TITLE
No way to activate addon on last beta blender 2.8 with linux ubuntu 18.04 

### ISSUE THREAD

**Issue by sramauge** [bblanimation/abs-plastic-materials#1]
Sorry i couldn't copy the log of the error, so i made a screen capture

![Sans titre](https://user-images.githubusercontent.com/42722419/60526777-475f7380-9cf1-11e9-949c-df1c79d80927.jpg)

thanks

**Comment by bblanimation** [comment]
Thank you for reporting this issue! numpy is a core module for ABS Plastic Materials – it looks like this version of ubuntu does not come with the module, so you'll need to install the module separately: https://www.swarthmore.edu/NatSci/mzucker1/e19_s2016/install_python_numpy_scipy_matplotlib.html

Future versions of ABS Plastic Materials will not run with a numpy module dependency though – keep an eye out for a new release of the addon soon after Blender 2.80 is officially released!
